###
POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "Carolinssss",
    "phone": "123457233222",
    "email": "12343sss1w12@gmail.com",
    "online_status": "TRUE",
    "last_online": "2023-10-28 22:16:00"
}