###
POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "Caro",
    "phone": "123457",
    "email": "12343@gmail.com",
    "online_status": "TRUE",
    "last_online": "2023-10-28 22:16:00"
}